import {chromium,expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:process.env.HEADED!=='1'});
const base=process.env.GAME_URL??'http://127.0.0.1:5173';
const checks=[];
try{
  const blocked=await browser.newContext();await blocked.addInitScript(()=>{Storage.prototype.setItem=()=>{throw new Error('storage blocked');};});const p=await blocked.newPage();await p.goto(base);await p.getByRole('button',{name:'ゲーム開始',exact:true}).click();await expect(p.locator('#hud')).toBeVisible({timeout:6000});await expect(p.locator('#save-warning')).toBeVisible();await p.getByRole('button',{name:'数字錠の引き出し',exact:true}).click();await expect(p.getByLabel('3桁の暗証番号')).toBeVisible({timeout:6000});await p.getByLabel('3桁の暗証番号').fill('243');await p.getByRole('button',{name:'解錠する',exact:true}).click();await expect(p.locator('.reward-label')).toContainText('紙片');checks.push('storage unavailable still playable');await blocked.close();
  const corrupt=await browser.newContext();await corrupt.addInitScript(()=>{localStorage.setItem('old-inn-escape:v1','broken-json');});const c=await corrupt.newPage();await c.goto(base);await expect(c.getByRole('button',{name:'ゲーム開始',exact:true})).toBeVisible();checks.push('corrupt save starts safely');await corrupt.close();
  const unavailable=await browser.newContext();await unavailable.route('**/assets/crest.png',route=>route.abort());const u=await unavailable.newPage();await u.goto(base);await expect(u.getByRole('heading',{name:'ゲームを表示できませんでした',exact:true})).toBeVisible();await expect(u.getByRole('button',{name:'再読み込み',exact:true})).toBeVisible();checks.push('asset failure explicit retry');await unavailable.close();
  const noGpu=await browser.newContext();await noGpu.addInitScript(()=>{const native=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(kind,...args){return kind==='webgl2'||kind==='webgl'?null:native.call(this,kind,...args);};});const g=await noGpu.newPage();await g.goto(base);await expect(g.locator('.dialog')).toContainText('WebGL 2');await expect(g.getByRole('button',{name:'再読み込み',exact:true})).toBeVisible();checks.push('WebGL unavailable explicit retry');await noGpu.close();
  const loss=await browser.newContext();const l=await loss.newPage();await l.goto(base);await l.getByRole('button',{name:'ゲーム開始',exact:true}).click();await expect(l.locator('#hud')).toBeVisible({timeout:6000});await l.locator('#world').evaluate(canvas=>{canvas.dispatchEvent(new Event('webglcontextlost',{cancelable:true}));});await expect(l.locator('.dialog')).toContainText('3D描画が一時停止');checks.push('WebGL context loss explicit retry');await loss.close();
  await writeFile('artifacts/playtest/resilience.json',JSON.stringify({checks,errors:[]},null,2));console.log(checks.join('\n'));
}finally{await browser.close();}
